name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Django Tests
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        working-directory: canvas_editor
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[dev]"

      - name: Run Tests
        working-directory: canvas_editor
        env:
          SECRET_KEY: django_ci_test_dummy_secret
        run: |
          mkdir -p ../reports

          coverage run manage.py test \
            --noinput \
            --verbosity=2 \
            --testrunner=xmlrunner.extra.djangotestrunner.XMLTestRunner \
            --pattern="test*.py"

          mv TEST-*.xml ../reports/ || true

      - name: Coverage report
        working-directory: canvas_editor
        run: |
          coverage xml -o ../reports/coverage.xml
          mv .coverage ../reports/coverage

      - name: Upload Test Reports
        uses: actions/upload-artifact@v5
        with:
          name: test-reports-py${{ matrix.python-version }}
          path: reports/

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Download coverage reports
        uses: actions/download-artifact@v6
        with:
          pattern: test-reports-py*

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Install coverage.py
        run: |
          pip install coverage

      - name: Combine coverage files
        run: |
          coverage combine test-reports-py*/coverage
          coverage xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # release v5.5.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
